#
# Loads default settings for spring services and csap
# NOTE: any values set in dev
#    
spring:

  profiles:
  
    active: desktop # Override using --spring.profiles.active=xxx,yyy,zzz
    include: 
    - app-defaults

---
spring.profiles: app-defaults

#
#  Servlet & Tomcat
#
server:
  port: 8080
  tomcat:
    max-threads: 50
  servlet:
    context-path: /
    session:
      persistent: false
      cookie:
        name: ${mySessionCookie:JSESSIONID}
  error:
    include-stacktrace: always
    
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

#
#  spring actuator endpoints
# 
management: 
  
  endpoints:
    web:
      base-path: /devOps
      exposure:
        include: "*"
      
info:
  build.profile: ${spring.profiles.active}
  build.artifact: "Maven: @project.artifactId@"
  build.name: "@project.name@"
  build.description: "@project.description@"
  build.version: "@project.version@"
 
#
#  Core Spring
#
spring:

  devtools.restart.additional-exclude: "**/*.jmx,**/*.csv,**/*.json"
  
  mail:
    host: "${mailServer:smtp.yourcompany.com}"
    port: "${mailPort:25}"
    
  output:
    ansi:
      enabled: never 
  resources: 
    cache:
      period: 32000000

  aop:
    proxy-target-class: true
  thymeleaf:
    mode: HTML


      