#
# Loads default settings for spring services and csap
# NOTE: any values set in dev
#    
spring:

  profiles:
  
    active: desktop # Override using --spring.profiles.active=xxx,yyy,zzz
    include: 
    - app-defaults

---
spring.profiles: app-defaults


#
#  Servlet & Tomcat
#
server:
  port: 8080
  tomcat:
    max-threads: 50
  servlet:
    context-path: /
    session:
      persistent: false
      cookie:
        name: ${mySessionCookie:JSESSIONID}
  error:
    include-stacktrace: always
    
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

#
#  spring actuator endpoints
# 
management: 
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
      
info:
  build.profile: ${spring.profiles.active}
  build.artifact: "Maven: @project.artifactId@"
  build.name: "@project.name@"
  build.description: "@project.description@"
  build.version: "@project.version@"


#
# security setup:
#   - deploy keycloak via docker
#   - add test realm:  csap-default
#     - add service client: csap-sevice
#         - roles: ViewRole, AdminRole, BuildRole, InfraRole
#         - enable service account, add service account roles for client (all of the above)
#         - update the client credential (oathSecret) and oathHostUrl environment variables
#     - add UI client: csap-ui
#   - add test user: testuser,testpass
#   - add test client: csap, with test roles: ViewRole
#   - add test scope: csap-roles-scope
#     - set token name: csap-claim-name
#
my-examples:
  security:
    enabled: true
    oath-user-token-name: "csap-service-claim"
    oath-service-claim-name: "csap-service"
    oath-client-service-name: "keycloak-service-auth"
    

#
#  Core Spring
#
spring:

  devtools.restart.additional-exclude: "**/*.jmx,**/*.csv,**/*.json"
  
  mail:
    host: "${mailServer:smtp.yourcompany.com}"
    port: "${mailPort:25}"
    
  output:
    ansi:
      enabled: never 
  resources: 
    cache:
      period: 32000000

  aop:
    proxy-target-class: true
    
  thymeleaf:
    mode: HTML

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${oathHostPort:localhost:8080}/auth/realms/csap-default/protocol/openid-connect/certs
          
      client:
      
        registration:
        
          keycloak-user-auth:
            client-id: csap-ui
            client-secret: ${oauthSecret:xx-xx-xx-xx-xx}
            clientName: "Keycloak: User authentication and Authorization"
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
              - csap-roles-scope
              
              
          #
          # Requires keycloak service role enabled
          #
          keycloak-service-auth:
            client-id: csap-service
            client-secret: ${oauthSecret:xx-xx-xx-xx-xx}
            clientName: "Keycloak: client_credentials"
            authorization-grant-type: client_credentials
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
              - csap-roles-scope
#            
        provider:
        
          keycloak-user-auth:
            authorization-uri: http://${oathHostPort:localhost:8080}/auth/realms/csap-default/protocol/openid-connect/auth
            token-uri: http://${oathHostPort:localhost:8080}/auth/realms/csap-default/protocol/openid-connect/token
            user-info-uri: http://${oathHostPort:localhost:8080}/auth/realms/csap-default/protocol/openid-connect/userinfo
            jwk-set-uri: http://${oathHostPort:localhost:8080}/auth/realms/csap-default/protocol/openid-connect/certs
            user-name-attribute: preferred_username
            
            
          keycloak-service-auth:
            issuer-uri: http://csap-dev01.lab.sensus.net:8090/auth/realms/csap-default
      
      
      
      
      
      
      
      
      
      
      