#
# Loads default settings for spring services and csap
# NOTE: any values set in dev
#    
spring:

  profiles:
  
    active: my-dev 

---
spring.config:
    activate:
      on-profile: "my-dev"

#
#  Servlet & Tomcat
#
server:
  port: 8080
  
  tomcat:
    mbeanregistry:
      enabled: true
    
    threads:
      max: 100
    
  servlet:
    context-path: /
    session:
      persistent: false
      cookie:
        name: ${mySessionCookie:JSESSIONID}
  error:
    include-stacktrace: always
    
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

#
#  spring actuator endpoints
# 
management: 
  
  endpoints:
    web:
      base-path: /devOps
      exposure:
        include: "*"
      
info:
  build:
    profile: "${spring.profiles.active}"
    artifact: "Maven: @project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
 
#
#  Core Spring
#
spring.jpa.properties.hibernate.generate_statistics: true
spring:
  jpa:
  
  
    show-sql: false
  
    hibernate:
      ddl-auto: create-drop
      
    
    

  devtools.restart.additional-exclude: "**/*.jmx,**/*.csv,**/*.json"
  
  web:
    resources:
      cache:
        period: 32000000
  
  mail:
    host: "${mailServer:smtp.yourcompany.com}"
    port: "${mailPort:25}"
    
  output:
    ansi:
      enabled: never

  aop:
    proxy-target-class: true
    
  thymeleaf:
    mode: HTML


      